import { VerificationRequest } from '../../src/domain/types';

const baseScripts = {
  test: 'jest',
  'test:unit': 'jest --selectProjects unit',
  'test:integration': 'jest --selectProjects integration',
};

export const safeDocsPr: VerificationRequest = {
  repoOwner: 'octo',
  repoName: 'demo',
  repoId: 'octo/demo',
  pullNumber: 1,
  title: 'Document the verification gate',
  body: 'Docs-only update for the verification README.',
  branchName: 'docs/update-readme',
  baseBranch: 'main',
  headSha: 'aaa0000001',
  author: 'alice',
  action: 'opened',
  commits: [{ message: 'docs: explain verification gate' }],
  changedFiles: [{ path: 'README.md', additions: 12, deletions: 1 }],
  checkRuns: [{ name: 'ci', status: 'completed', conclusion: 'success' }],
  reviewComments: [],
  repositoryFiles: {
    'README.md': '# docs',
  },
  repositoryScripts: baseScripts,
};

export const riskyAuthPr: VerificationRequest = {
  repoOwner: 'octo',
  repoName: 'demo',
  repoId: 'octo/demo',
  pullNumber: 2,
  title: 'Refactor auth session flow',
  body: 'This PR updates auth flow and session validation.',
  branchName: 'copilot/refactor-auth',
  baseBranch: 'main',
  headSha: 'abc0000002',
  author: 'copilot-swe-agent[bot]',
  action: 'opened',
  commits: [{ sha: 'abc', message: 'generated auth refactor by copilot agent' }],
  changedFiles: [
    { path: 'src/auth/session.service.ts', additions: 140, deletions: 20 },
    { path: 'src/auth/permission.guard.ts', additions: 35, deletions: 6 },
  ],
  checkRuns: [{ name: 'ci', status: 'completed', conclusion: 'success' }],
  reviewComments: [],
  repositoryFiles: {
    'src/auth/session.service.ts': `export function readSession() { return 'ok'; }`,
    'src/auth/permission.guard.ts': `import { readSession } from './session.service';\nexport const guard = () => readSession();`,
  },
  repositoryScripts: baseScripts,
};

export const migrationPr: VerificationRequest = {
  ...riskyAuthPr,
  pullNumber: 3,
  title: 'Add audit migration',
  branchName: 'feature/audit-migration',
  commits: [{ message: 'db: add migration' }],
  changedFiles: [
    { path: 'prisma/migrations/20260702000000_add_audit_table/migration.sql', additions: 40, deletions: 0 },
    { path: 'src/db/migrate.ts', additions: 20, deletions: 4 },
  ],
  repositoryFiles: {
    'src/db/migrate.ts': `export const migrate = () => 'ok';`,
  },
};

export const dependencyUpdatePr: VerificationRequest = {
  ...safeDocsPr,
  pullNumber: 4,
  title: 'Update dependencies',
  branchName: 'deps/update-lockfile',
  changedFiles: [
    { path: 'package.json', additions: 4, deletions: 2 },
    { path: 'package-lock.json', additions: 120, deletions: 50 },
  ],
  repositoryFiles: {
    'package.json': '{"scripts":{"test":"jest"}}',
  },
};

export const agentLookingPr: VerificationRequest = {
  ...riskyAuthPr,
  pullNumber: 5,
  title: 'Automated update for API layer',
  body: 'This PR was generated by Claude to automate a wide refactor.',
  branchName: 'claude/large-api-refactor',
  changedFiles: Array.from({ length: 12 }, (_, index) => ({
    path: `src/api/file-${index}.ts`,
    additions: 80,
    deletions: 10,
    content: index === 0 ? '// auto-generated helper\nexport const x = 1;' : 'export const y = 2;',
  })),
  checkRuns: [{ name: 'ci', status: 'completed', conclusion: 'failure' }],
};
