import {
  ChangedFile,
  RiskLevel,
  RiskFinding,
  RiskSignalEvaluation,
  TestImpactResult,
  VerificationPolicy,
  VerificationRequest,
} from "../domain/types";

function isDocsFile(path: string): boolean {
  return /(^docs\/|\/docs\/|readme|changelog|\.mdx?$)/i.test(path);
}

function hasPattern(files: ChangedFile[], pattern: RegExp): boolean {
  return files.some((file) => pattern.test(file.path));
}

const riskCategories: Array<[string, RegExp, string]> = [
  [
    "auth",
    /(auth|session|permission|rbac|acl)/i,
    "Auth, session, or permission paths changed.",
  ],
  [
    "payment",
    /(payment|billing|invoice|checkout|subscription)/i,
    "Payment or billing paths changed.",
  ],
  [
    "migration",
    /(migration|migrations|schema\.sql|prisma\/migrations)/i,
    "Database migration files changed.",
  ],
  [
    "env",
    /(^|\/)(\.env|config|secrets?|settings|terraform\.tfvars)/i,
    "Configuration or secret-sensitive files changed.",
  ],
  [
    "dependencyLockfile",
    /(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|poetry\.lock|requirements\.txt|package\.json)/i,
    "Dependency manifest or lockfile changed.",
  ],
  [
    "infrastructure",
    /(docker-compose|terraform|helm|k8s|kubectl|ansible|infra|\.github\/workflows)/i,
    "Infrastructure or automation files changed.",
  ],
  [
    "apiContract",
    /(openapi|swagger|graphql|schema|controller|routes?)/i,
    "API contract or transport layer files changed.",
  ],
];

function normalizePath(path: string): string {
  return path.replace(/\\/g, "/");
}

function findUncategorizedFiles(files: ChangedFile[]): string[] {
  return [
    ...new Set(
      files
        .map((file) => normalizePath(file.path))
        .filter(
          (path) =>
            !isDocsFile(path) &&
            !riskCategories.some(([, pattern]) => pattern.test(path)),
        ),
    ),
  ].sort();
}

function tokenize(value: string): string[] {
  return value
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
}

function hasToken(value: string, token: string): boolean {
  const normalizedToken = token.toLowerCase();
  return tokenize(value).includes(normalizedToken);
}

function branchHasIndicator(branchName: string, indicator: string): boolean {
  return hasToken(branchName, indicator);
}

function hasAgentBodySignal(text: string): boolean {
  return /(generated by|ai-assisted|copilot|claude|cursor|codex|agentic)/i.test(
    text,
  );
}

function hasAgentCommitSignal(message: string): boolean {
  return /(copilot|claude|cursor|codex|generated|agentic|swe-agent)/i.test(
    message,
  );
}

function hasStrongBotAuthorSignal(author: string): boolean {
  if (/\[bot\]$/i.test(author)) {
    return true;
  }
  return /(copilot|claude|cursor|codex|swe-agent)/i.test(author);
}

function extractAddedPatchLines(patch: string): string[] {
  return patch
    .split("\n")
    .filter((line) => line.startsWith("+") && !line.startsWith("+++"))
    .map((line) => line.slice(1));
}

function calculateRiskLevel(riskScore: number): RiskLevel {
  if (riskScore >= 75) {
    return RiskLevel.CRITICAL;
  }
  if (riskScore >= 45) {
    return RiskLevel.HIGH;
  }
  if (riskScore >= 20) {
    return RiskLevel.MEDIUM;
  }
  return RiskLevel.LOW;
}

function hasDeletedTests(files: ChangedFile[]): boolean {
  return files.some(
    (file) =>
      /(^|\/)(tests?|__tests__|specs?)\/|(\.|_)(spec|test)\./i.test(
        file.path,
      ) && ["removed", "deleted"].includes((file.status ?? "").toLowerCase()),
  );
}

function hasSkippedTests(files: ChangedFile[]): boolean {
  return files.some((file) => {
    if (!file.patch) {
      return false;
    }
    return extractAddedPatchLines(file.patch).some((line) =>
      /(\b(it|test|describe)\.skip\s*\(|\b(xit|xtest)\s*\()/i.test(line),
    );
  });
}

function hasExcessiveMocks(files: ChangedFile[]): boolean {
  let mockCount = 0;
  for (const file of files) {
    if (!file.patch) {
      continue;
    }
    for (const line of extractAddedPatchLines(file.patch)) {
      if (
        /\b(jest|vi)\.mock\s*\(|\bmock(Return|Resolved)Value\s*\(/i.test(line)
      ) {
        mockCount += 1;
      }
    }
  }
  return mockCount >= 8;
}

interface SignalObservation {
  triggered: boolean;
  observedValue?: string | number | boolean;
  threshold?: string | number;
}

interface RiskSignalDefinition {
  code: string;
  weightKey: string;
  reason: string;
  fallbackWeight?: number;
  evaluate: () => SignalObservation;
}

export function scoreRisk(
  request: VerificationRequest,
  policy: VerificationPolicy,
  testImpact: TestImpactResult,
): {
  riskScore: number;
  riskLevel: RiskLevel;
  riskFindings: RiskFinding[];
  evaluatedSignals: RiskSignalEvaluation[];
  likelyAgentAuthored: boolean;
  uncategorizedFiles: string[];
} {
  const files = request.changedFiles;
  const docsOnly =
    files.length > 0 && files.every((file) => isDocsFile(file.path));
  const weight = (key: string) => policy.riskWeights[key] ?? 0;

  const strongBranchSignal = policy.heuristics.branchIndicators.some(
    (indicator) => branchHasIndicator(request.branchName, indicator),
  );
  const strongAuthorSignal = hasStrongBotAuthorSignal(request.author);
  const weakSignals = [
    hasAgentBodySignal(request.body),
    request.commits.some((commit) => hasAgentCommitSignal(commit.message)),
    /(this pr|this change|automated update)/i.test(request.body) &&
      files.length >= 8,
  ].filter(Boolean).length;

  const likelyAgentAuthored =
    strongAuthorSignal || strongBranchSignal || weakSignals >= 2;
  const totalLineDelta = files.reduce(
    (sum, file) => sum + (file.additions ?? 0) + (file.deletions ?? 0),
    0,
  );
  const generatedText = files.some(
    (file) =>
      /(generated|auto-generated|do not edit)/i.test(file.content ?? "") ||
      /(generated|auto-generated|do not edit)/i.test(file.patch ?? ""),
  );
  const truncatedEvidence =
    request.evidenceFindings?.filter((finding) =>
      finding.startsWith("repository-context-truncated:"),
    ) ?? [];
  const signalDefinitions: RiskSignalDefinition[] = [
    {
      code: "agent-authored",
      weightKey: "agentAuthored",
      reason:
        "Branch, body, or commit metadata strongly suggests agent-authored changes.",
      evaluate: () => ({
        triggered: !docsOnly && likelyAgentAuthored,
        observedValue: likelyAgentAuthored,
      }),
    },
    ...riskCategories.map(([code, pattern, reason]) => ({
      code,
      weightKey: code,
      reason,
      evaluate: (): SignalObservation => ({
        triggered: !docsOnly && hasPattern(files, pattern),
        observedValue: files.filter((file) => pattern.test(file.path)).length,
      }),
    })),
    {
      code: "large-pr",
      weightKey: "largePr",
      reason:
        "The PR is broad, which makes safe review and verification harder.",
      evaluate: () => ({
        triggered: !docsOnly && (files.length >= 12 || totalLineDelta >= 700),
        observedValue: `${files.length} files, ${totalLineDelta} changed lines`,
        threshold: "12 files or 700 changed lines",
      }),
    },
    {
      code: "generated-text",
      weightKey: "generatedText",
      reason: "Generated-looking code or prose was detected in the diff.",
      evaluate: () => ({
        triggered: !docsOnly && generatedText,
        observedValue: generatedText,
      }),
    },
    {
      code: "missing-tests",
      weightKey: "missingTests",
      reason:
        "No nearby tests were changed or mapped for risky source changes.",
      evaluate: () => ({
        triggered: !docsOnly && testImpact.missingTestCoverage.length > 0,
        observedValue: testImpact.missingTestCoverage.length,
        threshold: 0,
      }),
    },
    {
      code: "deleted-tests",
      weightKey: "deletedTests",
      reason: "Deleted test files were detected in this pull request.",
      evaluate: () => ({
        triggered: !docsOnly && hasDeletedTests(files),
      }),
    },
    {
      code: "skipped-tests",
      weightKey: "skippedTests",
      reason: "Skipped tests were introduced in patch changes.",
      evaluate: () => ({
        triggered: !docsOnly && hasSkippedTests(files),
      }),
    },
    {
      code: "excessive-mocks",
      weightKey: "excessiveMocks",
      reason: "Heavy mocking usage was detected in added patch lines.",
      evaluate: () => ({
        triggered: !docsOnly && hasExcessiveMocks(files),
      }),
    },
    {
      code: "evidence-truncated",
      weightKey: "evidenceTruncated",
      fallbackWeight: 5,
      reason: `Repository context fetch was truncated (${truncatedEvidence.join(", ")}).`,
      evaluate: () => ({
        triggered: !docsOnly && truncatedEvidence.length > 0,
        observedValue: truncatedEvidence.length,
        threshold: 0,
      }),
    },
  ];

  const evaluatedSignals = signalDefinitions.map(
    (definition): RiskSignalEvaluation => {
      const observation = definition.evaluate();
      return {
        code: definition.code,
        triggered: observation.triggered,
        weight: weight(definition.weightKey) || definition.fallbackWeight || 0,
        reason: definition.reason,
        ...(observation.observedValue === undefined
          ? {}
          : { observedValue: observation.observedValue }),
        ...(observation.threshold === undefined
          ? {}
          : { threshold: observation.threshold }),
      };
    },
  );
  const findings = evaluatedSignals
    .filter((signal) => signal.triggered)
    .map(({ code, weight: signalWeight, reason }) => ({
      code,
      weight: signalWeight,
      reason,
    }));

  const riskScore = Math.min(
    100,
    findings.reduce((sum, finding) => sum + finding.weight, 0),
  );

  const normalizedRiskScore = docsOnly ? Math.min(riskScore, 8) : riskScore;

  return {
    riskScore: normalizedRiskScore,
    riskLevel: calculateRiskLevel(normalizedRiskScore),
    riskFindings: findings,
    evaluatedSignals,
    likelyAgentAuthored,
    uncategorizedFiles: docsOnly ? [] : findUncategorizedFiles(files),
  };
}
