import {
  ChangedFile,
  RiskFinding,
  TestImpactResult,
  VerificationPolicy,
  VerificationRequest,
} from "../domain/types";

function isDocsFile(path: string): boolean {
  return /(^docs\/|\/docs\/|readme|changelog|\.mdx?$)/i.test(path);
}

function hasPattern(files: ChangedFile[], pattern: RegExp): boolean {
  return files.some((file) => pattern.test(file.path));
}

export function scoreRisk(
  request: VerificationRequest,
  policy: VerificationPolicy,
  testImpact: TestImpactResult,
): {
  riskScore: number;
  riskFindings: RiskFinding[];
  likelyAgentAuthored: boolean;
} {
  const findings: RiskFinding[] = [];
  const files = request.changedFiles;
  const docsOnly =
    files.length > 0 && files.every((file) => isDocsFile(file.path));
  const weight = (key: string) => policy.riskWeights[key] ?? 0;

  const agentIndicators = [
    policy.heuristics.branchIndicators.some((indicator) =>
      request.branchName.toLowerCase().includes(indicator.toLowerCase()),
    ),
    /(generated by|ai-assisted|copilot|claude|cursor|codex|agentic)/i.test(
      request.body,
    ),
    request.commits.some((commit) =>
      /(copilot|claude|cursor|codex|agent|generated)/i.test(commit.message),
    ),
    /(this pr|this change|automated update)/i.test(request.body) &&
      files.length >= 8,
  ].filter(Boolean).length;

  const likelyAgentAuthored = agentIndicators >= 2;
  if (likelyAgentAuthored && !docsOnly) {
    findings.push({
      code: "agent-authored",
      weight: weight("agentAuthored"),
      reason:
        "Branch, body, or commit metadata strongly suggests agent-authored changes.",
    });
  }

  const categories: Array<[string, RegExp, string]> = [
    [
      "auth",
      /(auth|session|permission|rbac|acl)/i,
      "Auth, session, or permission paths changed.",
    ],
    [
      "payment",
      /(payment|billing|invoice|checkout|subscription)/i,
      "Payment or billing paths changed.",
    ],
    [
      "migration",
      /(migration|migrations|schema\.sql|prisma\/migrations)/i,
      "Database migration files changed.",
    ],
    [
      "env",
      /(^|\/)(\.env|config|secrets?|settings|terraform\.tfvars)/i,
      "Configuration or secret-sensitive files changed.",
    ],
    [
      "dependencyLockfile",
      /(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|poetry\.lock|requirements\.txt|package\.json)/i,
      "Dependency manifest or lockfile changed.",
    ],
    [
      "infrastructure",
      /(docker-compose|terraform|helm|k8s|kubectl|ansible|infra|\.github\/workflows)/i,
      "Infrastructure or automation files changed.",
    ],
    [
      "apiContract",
      /(openapi|swagger|graphql|schema|controller|routes?)/i,
      "API contract or transport layer files changed.",
    ],
  ];

  if (!docsOnly) {
    for (const [code, pattern, reason] of categories) {
      if (hasPattern(files, pattern)) {
        findings.push({ code, weight: weight(code), reason });
      }
    }
  }

  const totalLineDelta = files.reduce(
    (sum, file) => sum + (file.additions ?? 0) + (file.deletions ?? 0),
    0,
  );
  if (!docsOnly && (files.length >= 12 || totalLineDelta >= 700)) {
    findings.push({
      code: "large-pr",
      weight: weight("largePr"),
      reason:
        "The PR is broad, which makes safe review and verification harder.",
    });
  }

  const generatedText = files.some(
    (file) =>
      /(generated|auto-generated|do not edit)/i.test(file.content ?? "") ||
      /(generated|auto-generated|do not edit)/i.test(file.patch ?? ""),
  );
  if (!docsOnly && generatedText) {
    findings.push({
      code: "generated-text",
      weight: weight("generatedText"),
      reason: "Generated-looking code or prose was detected in the diff.",
    });
  }

  if (!docsOnly && testImpact.missingTestCoverage.length > 0) {
    findings.push({
      code: "missing-tests",
      weight: weight("missingTests"),
      reason:
        "No nearby tests were changed or mapped for risky source changes.",
    });
  }

  const truncatedEvidence =
    request.evidenceFindings?.filter((finding) =>
      finding.startsWith("repository-context-truncated:"),
    ) ?? [];
  if (!docsOnly && truncatedEvidence.length > 0) {
    findings.push({
      code: "evidence-truncated",
      weight: weight("evidenceTruncated") || 5,
      reason: `Repository context fetch was truncated (${truncatedEvidence.join(", ")}).`,
    });
  }

  const riskScore = Math.min(
    100,
    findings.reduce((sum, finding) => sum + finding.weight, 0),
  );

  return {
    riskScore: docsOnly ? Math.min(riskScore, 8) : riskScore,
    riskFindings: findings,
    likelyAgentAuthored,
  };
}
